# Generated by Django 4.2.1 on 2023-05-29 06:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geolocation_app", "0002_place_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, unique=True
            ),
        ),
    ]
